import { defineConfig } from 'vitest/config';
import { svelte } from '@sveltejs/vite-plugin-svelte';

export default defineConfig({
  test: {
    projects: [
      {
        test: {
          name: 'main',
          include: ['tests/main/**/*.test.js', 'tests/shared/**/*.test.js'],
          environment: 'node',
        },
      },
      {
        test: {
          name: 'renderer',
          include: ['tests/renderer/**/*.test.js', 'tests/renderer/**/*.test.ts'],
          exclude: ['tests/renderer/components/**'],
          environment: 'node',
        },
      },
      {
        plugins: [svelte({ hot: false })],
        resolve: {
          conditions: ['browser'],
        },
        test: {
          name: 'components',
          include: ['tests/renderer/components/**/*.test.{js,ts}'],
          environment: 'jsdom',
          setupFiles: ['tests/renderer/components/_setup.ts'],
          css: { modules: { classNameStrategy: 'non-scoped' } },
        },
      },
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      include: [
        'frontend/observatory/runtime/**/*.ts',
        'frontend/observatory/components/**/*.svelte',
        'frontend/observatory/App.svelte',
        'src/renderer/lib/utils/enrich-agents.ts',
        'src/main/logger.js',
        'src/main/agent-event-receiver.js',
        'src/main/action-policy.js',
        'src/main/action-policy-session.js',
        'src/main/execution-policy.js',
        'src/main/execution-runtime.js',
        'src/main/action-route-check.js',
        'src/main/action-catalog-check.js',
        'src/main/execution-binding.js',
        'src/main/execution-approval.js',
        'src/main/action-confirmation.js',
        'src/main/action-confirmation-terminal.js',
        'src/main/action-execution.js',
        'src/main/action-execution-cli.js',
        'src/main/action-mcp.js',
        'src/main/action-mcp-status.js',
        'src/main/action-observation-schema.js',
        'src/main/action-observation-server.js',
        'src/main/action-observation-client.js',
        'src/main/action-mcp-config.js',
        'src/main/action-mcp-catalog.js',
        'src/main/action-mcp-stdio.js',
        'src/main/mcp-stdio-transport.js',
        'src/main/mcp-gateway.js',
        'src/main/mcp-gateway-grants.js',
        'src/main/mcp-gateway-secrets.js',
        'src/main/mcp-gateway-route.js',
        'src/main/mcp-gateway-tls.js',
        'src/main/mcp-gateway-http-peer.js',
        'src/main/mcp-gateway-http-wire.js',
        'src/main/mcp-gateway-peer.js',
        'src/main/mcp-gateway-schema.js',
        'src/main/mcp-gateway-cli.js',
        'src/main/action-mcp-review.js',
        'src/main/action-mcp-endpoint.js',
        'src/main/action-mcp-connect.js',
        'src/main/action-policy-hook.js',
        'src/main/handoff-live.js',
        'src/main/handoff-send.js',
        'src/main/handoff-live-cli.js',
        'src/main/handoff-import.js',
        'src/main/handoff-reader.js',
        'src/main/agent-inventory.js',
        'src/main/inventory-reader.js',
        'src/main/inventory-config.js',
        'src/main/inventory-profiles.js',
        'src/main/inventory-packages.js',
        'src/main/inventory-git.js',
        'src/main/inventory-snapshot.js',
        'src/main/inventory-snapshot-diff.js',
        'src/main/inventory-snapshot-files.js',
        'src/main/inventory-snapshot-cli.js',
        'src/main/inventory-tool-catalog.js',
        'src/main/static-analysis.js',
        'src/main/local-security-review.js',
        'src/main/local-security-ipc.js',
        'src/main/static-code-catalog.js',
        'src/main/static-javascript.js',
        'src/main/static-javascript-ast.js',
        'src/main/static-javascript-scope.js',
        'src/main/static-javascript-values.js',
        'src/main/static-javascript-invocation.js',
        'src/main/static-javascript-flow.js',
        'src/main/static-javascript-modules.js',
        'src/main/static-python.js',
        'src/main/static-python-tree.js',
        'src/main/static-python-string.js',
        'src/main/static-python-scope.js',
        'src/main/static-python-values.js',
        'src/main/static-python-invocation.js',
        'src/main/static-python-flow.js',
        'src/main/static-python-functions.js',
        'src/main/static-import-values.js',
        'src/main/static-import-skill.js',
        'src/main/static-import-sarif.js',
        'src/main/static-import-mcp.js',
        'src/main/static-import-normalize.js',
        'src/main/static-report-import.js',
        'src/main/static-import-cli.js',
        'src/main/static-analysis-files.js',
        'src/main/static-analysis-cli.js',
        'src/main/static-analysis-rules.js',
        'src/main/static-command-parser.js',
        'src/main/static-command-analysis.js',
        'src/main/static-command-redirections.js',
        'src/main/static-command-file.js',
        'src/main/static-instruction-analysis.js',
        'src/main/static-instruction-catalog.js',
        'src/main/static-config-analysis.js',
        'src/main/audit-logger.js',
        'src/main/audit-index.js',
        'src/main/audit-index-query.js',
        'src/main/audit-index-rebuild.js',
        'src/main/config-manager.js',
        'src/main/baselines.js',
        'src/main/process-utils.js',
        'src/main/application-groups.js',
        'src/main/process-scanner.js',
        'src/main/resource-monitor.js',
        'src/main/platform/windows-resources.js',
        'src/main/platform/windows-tcp.js',
        'src/main/platform/windows-observer.js',
        'src/main/file-watcher.js',
        'src/main/ipc-batcher.js',
        'src/main/file-access-batching.js',
        'src/main/network-monitor.js',
        'src/main/ide-extension-detector.js',
        'src/main/wsl-detector.js',
        'src/main/llm-runtime-detector.js',
        'src/main/platform/posix-shared.js',
        'src/main/platform/proc-snapshot-protocol.js',
        'src/main/platform/etw-file-protocol.js',
        'src/main/platform/etw-file-schema.js',
        'src/main/platform/etw-file-health.js',
        'src/main/platform/etw-file-diagnostics.js',
        'src/main/platform/etw-file-supervisor.js',
        'src/main/platform/proc-snapshot-client.js',
        'src/main/platform/process-snapshot.js',
        'src/main/platform/linux.js',
        'src/main/platform/linux-process-map.js',
        'src/main/platform/darwin.js',
        'src/main/platform/win32.js',
        'src/main/platform/index.js',
        'src/main/anomaly-detector.js',
        'src/main/ai-analysis.js',
        'src/main/exports.js',
        'src/main/tray-icon.js',
        'src/main/ipc-handlers.js',
        'src/main/sequence-rule-loader.js',
        'src/main/sequence-engine.js',
        'src/main/sequence-evidence.js',
        'src/main/sequence-related.js',
        'src/main/process-lineage.js',
        'src/renderer/lib/utils/risk-scoring.js',
        'src/renderer/lib/utils/threat-report.js',
        'src/renderer/lib/stores/toast.ts',
        'src/shared/constants.js',
        'src/shared/skill-path.js',
        'src/shared/process-request.js',
      ],
    },
  },
});
