/**
 * @file threat-report.js — Generate printable HTML threat report
 * @module renderer/utils/threat-report
 * @since 0.2.0
 */

function esc(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Open a printable HTML threat report in a new window.
 * @param {Object} result - Analysis result (riskRating, summary, findings, recommendations)
 * @param {Object} counts - { totalFiles, totalSensitive, totalAgents, totalNet }
 */
export function openThreatReport(result, counts) {
  const now = new Date().toLocaleString();
  const colors = {
    CLEAR: '#38A169',
    LOW: '#38A169',
    MEDIUM: '#ED8936',
    HIGH: '#ED8936',
    CRITICAL: '#E53E3E',
  };
  const rc = colors[result.riskRating] || '#ED8936';
  const { totalFiles, totalSensitive, totalAgents, totalNet } = counts;

  const findings = result.findings?.length
    ? `<div class="sec"><div class="t">FINDINGS</div><ul>${result.findings.map((f) => `<li>${esc(f)}</li>`).join('')}</ul></div>`
    : '';
  const recs = result.recommendations?.length
    ? `<div class="sec"><div class="t">RECOMMENDATIONS</div><ul>${result.recommendations.map((r) => `<li>${esc(r)}</li>`).join('')}</ul></div>`
    : '';

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>AEGIS Threat Report</title>
<style>body{font-family:'Segoe UI',sans-serif;background:#0a0e17;color:#E0E5EC;margin:0;padding:24px}
h1{color:#7a8a9e;font-size:28px;margin-bottom:4px}.meta{color:#8896A6;font-size:12px;margin-bottom:20px}
.g{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:16px 0}
.s{text-align:center;padding:12px;background:#12162b;border-radius:8px}
.sv{font-size:24px;font-weight:700}.sl{font-size:10px;color:#8896A6;letter-spacing:1px}
.sec{background:#12162b;border-radius:10px;padding:16px;margin-bottom:16px}
.t{font-size:12px;letter-spacing:2px;color:#8896A6;margin-bottom:8px;font-weight:700}
.r{display:inline-block;padding:6px 20px;border-radius:12px;font-weight:800;font-size:18px;letter-spacing:2px;color:#fff;background:${rc}}
ul{margin:8px 0;padding-left:20px}li{margin:4px 0;color:#c8d0da}
.f{margin-top:20px;text-align:center;color:#8896A6;font-size:11px}
@media print{body{background:#fff;color:#222}.sec,.s{background:#f5f5f5;border:1px solid #ddd}h1{color:#2a9d8f}.r{border:2px solid ${rc}}}</style></head>
<body><h1>AEGIS Threat Analysis Report</h1><div class="meta">Generated: ${now}</div>
<div class="g">
<div class="s"><div class="sv" style="color:#7a8a9e">${totalFiles}</div><div class="sl">FILES ACCESSED</div></div>
<div class="s"><div class="sv" style="color:#c87a7a">${totalSensitive}</div><div class="sl">SENSITIVE ALERTS</div></div>
<div class="s"><div class="sv" style="color:#7a8a9e">${totalAgents}</div><div class="sl">AGENTS DETECTED</div></div>
<div class="s"><div class="sv" style="color:#7a8a9e">${totalNet}</div><div class="sl">NETWORK CONNECTIONS</div></div>
</div>
<div class="sec"><div class="t">THREAT LEVEL</div><span class="r">${esc(result.riskRating || 'UNKNOWN')}</span></div>
<div class="sec"><div class="t">SUMMARY</div><p>${esc(result.summary || '').replace(/\n/g, '<br>')}</p></div>
${findings}${recs}
<div class="f">Generated by AEGIS — AI Agent Privacy Shield</div></body></html>`;

  window.aegis.openThreatReport(html);
}
